/**
 * 
 */
package com.avc.mis.beta.entities.enums;

/**
 * @author Zvi
 *
 */
public enum ProcessName {
	CASHEW_ORDER,
	GENERAL_ORDER,
	CASHEW_RECEIPT,
	GENERAL_RECEIPT,
	CASHEW_RECEIPT_QC,
	ROASTED_CASHEW_QC,
	VINA_CONTROL_QC,
	SAMPLE_QC,
	SUPPLIER_QC,
	SAMPLE_RECEIPET, 
	STORAGE_TRANSFER, 
	STORAGE_RELOCATION, 
	CASHEW_CLEANING,
	CASHEW_ROASTING,
	CASHEW_TOFFEE,
	PACKING,
	CONTAINER_BOOKING,
	CONTAINER_LOADING,
	CONTAINER_ARRIVAL,
	GENERAL_USE
	
}
